### ISSUE TITLE
Adding game-friendly keyboard recording as well

### ISSUE THREAD

**Issue by labtec901** [lugia19/DeltaMacros#1]
This script is the first one I have seen on the internet that actually is able to correctly input mouse movements for FPS games/Minecraft, so thank you so much for that.  Is it possible to integrate this script with a keyboard recorder/playback functionality as well?

**Comment by lugia19** [comment]
It already records/plays back keyboard inputs, I simply forgot to add it to the readme. Is there some game where it doesn't work?

**Comment by labtec901** [comment]
I was not able to play back keyboard inputs in Minecraft (Java edition)

**Comment by lugia19** [comment]
I'll test it and let you know - it's likely the send mode needs to be changed.

**Comment by lugia19** [comment]
It actually works fine for me in minecraft - have you tried running it as admin?

**Comment by labtec901** [comment]
I have been able to make it work in minecraft, but it seems only about 25% of the time.  When it doesn't work, I can check the currentscript_X.ahk file and there are no keyboard events recorded, only mouse.  Still trying to figure out how to replicate consistently.

**Comment by lugia19** [comment]
Email reply decided to not work, so I'll just reply normally.

Have you checked your CPU usage perhaps? The way I record mouse inputs is the most accurate I've found, but it's also highly CPU intensive.

Other than that, I'm at a loss as to what the problem might be.
